# Generated by Django 4.2 on 2026-06-20 22:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('ETA', 'Predicción de ETA'), ('TRAFFIC', 'Detección de Tráfico'), ('ANOMALY', 'Detección de Anomalías')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('row_count', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_for_training', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('ETA', 'Predicción de ETA'), ('TRAFFIC', 'Detección de Tráfico'), ('ANOMALY', 'Detección de Anomalías')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('training_data_size', models.IntegerField(default=0)),
                ('feature_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('ETA', 'Predicción de ETA'), ('TRAFFIC', 'Detección de Tráfico'), ('ANOMALY', 'Detección de Anomalías')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En ejecución'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('logs', models.TextField(blank=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_api.mlmodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_type', models.CharField(choices=[('ETA_ARRIVAL', 'ETA de Llegada'), ('ROUTE_CONGESTION', 'Congestión de Ruta'), ('ANOMALY_DETECTION', 'Detección de Anomalía')], max_length=50)),
                ('input_data', models.JSONField()),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('prediction_result', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_api.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_predictions_24h', models.IntegerField(default=0)),
                ('avg_confidence_24h', models.FloatField(default=0.0)),
                ('error_rate_24h', models.FloatField(default=0.0)),
                ('total_predictions_7d', models.IntegerField(default=0)),
                ('avg_confidence_7d', models.FloatField(default=0.0)),
                ('error_rate_7d', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_metrics', to='ml_api.mlmodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['model_type', '-trained_at'], name='ml_api_mlmo_model_t_b71e56_idx'),
        ),
        migrations.AddIndex(
            model_name='mlmodel',
            index=models.Index(fields=['is_active'], name='ml_api_mlmo_is_acti_85afa7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetversion',
            unique_together={('model_type', 'version')},
        ),
        migrations.AddIndex(
            model_name='trainingjob',
            index=models.Index(fields=['model_type', 'status'], name='ml_api_trai_model_t_016cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['prediction_type', 'created_at'], name='ml_api_pred_predict_c0506b_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['input_hash', 'expires_at'], name='ml_api_pred_input_h_b8a563_idx'),
        ),
    ]
